# Generated by Django 2.0.4 on 2018-04-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
    ]
